# Generated by Django 5.2 on 2025-05-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
